global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 1s
      api_version: v1
scrape_configs:
  - job_name: nodeRed_job
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics/
    scheme: http
    static_configs:
      - targets:
        - 141.72.13.25:1880